spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/muscuapp
    username: postgres
    password: Hampteau1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080